#+TITLE: Feature realization plan
#+AUTHOR: SSAD Team
#+DATE: [2017-08-17 Thu]
#+SETUPFILE: ./org-templates/level-0.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction
  This document holds the feature realization plan for oauth
  service. 

  
* Milestones
  This section contains the various milestones and the various issues to reach those milestones.


** Milesone I
*** Common Authentcation portal
    Implementation of CAS in JAVA
*** Issues
    1. Multiple VLEAD projects would have a single login.
    2. Portal for users to log in.
    3. Mechanism for user to remian logged in even after he starts using another portal.
    4. Register different projects of VLEAD with CAS.


** Milestone II
*** Google single sign on 
    use googles single sign
*** Issues
    1. Use relay tokens.
    2. Authorize users after authentication with google(Session time, Refresh tokens etc.)
    3. Implement SSO of google.


** Milestone III
*** Packages
    Develop packages for diffrent VLEAD portals for easy integration with CAS   
