#+TITLE: Feature realization plan
#+AUTHOR: SSAD Team
#+DATE: [2017-08-17 Thu]
#+SETUPFILE: ./org-templates/level-0.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction
  This document holds the feature realization plan for oauth
  service. 

  
* Milestones
  This section contains the various milestones and the various issues to reach those milestones.


** Milesone I
*** Common Authentcation portal
    Implementation of CAS in JAVA
*** Issues
    1. Multiple VLEAD projects would have a single login.
    2. Portal for users to log in.
    3. Mechanism for user to remian logged in even after he starts using another portal.
    4. Register different projects of VLEAD with CAS.


** Milestone II
*** Google single sign on 
    use googles single sign
*** Issues
    1. Use relay tokens.
    2. Authorize users after authentication with google(Session time, Refresh tokens etc.)
    3. Implement SSO of google.


** Milestone III
*** Packages
    Develop packages for diffrent VLEAD portals for easy integration with CAS   




Theme Initiaitive Feature Estimate
Common authentication portal Implementing the CAS
of JAVA Multiple VLEAD projects
would have a single login 3 days
Portal for users to log in 2 days
Mechanism for user to
remian logged in even after
he starts using another
portal
2 days
Register different projects
with VLEAD
5 days
Google single sign on
User does not have to
 on store password on the
in CAS
VLEAD
5 days
Authentication will be provi
ded by google
1 day
Relay tokens, authorization
of the users will be done
CAS portal
5 days
	       
