#+TITLE: CAS SERVER 
#+AUTHOR: VLEAD
#+DATE: [2017-09-22 Friday]
#+SETUPFILE: ../org-templates/level-1.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction 
  In todays meeting we want to discuss:

** R1 on 13-15th October
   1. As part of SSAD we have 2 Releases.
   2. Release 1 or R1 is going to take place from 13-15 October
   3. Proff Raghu Redd, Thirumal Sir and our team are expected to
      attend the meeting.
   4. Meeting consists of a 4 minute presentation of the work done by
      the team till now.

** Demo of using CAS Server

   Today we want to show a small demo where using a small client
   server, we get redirected to CAS SERVER. After logging in, we are
   redirected back to the client server which displays the name of the
   user.

   Everything takes place with the help of tickets generated by CAS.

   Documentation of the code is present [[../vlead-cas-overlay/index.org][here]]

** How to integrate with CAS
   1. Various online modules are present with can be easily set up to
      use CAS.
      The links to each module can be found here:
      FlASK:       [[https://github.com/cameronbwhite/Flask-CAS]]
      Django:      [[https://pypi.python.org/pypi/django-cas-client/]]
      Spring MVC:  [[https://mvnrepository.com/artifact/org.springframework.security/spring-security-cas-client]]
      Node Js:     [[https://www.npmjs.com/package/cas-client-node]]


   2. On CAS Server side we must add their domain name in the form of
      JSON files.

** Setting Up the Vagrant BOX
   Setting up the vagrant box, any virtual machine or and server can
   be a tricky job and method to set up is specified [[../deployment/index.org][here]]
   
** Frontend for the CAS Server
   Frontend is a key part of the server because every VLEAD portal
   user has to go through CAS service, hence it is necessary to
   discuss:
   1. Page layout
   2. Colour Scheme
   3. Favicon of vlead logo
   4. Vlead designs and images


* Work done after the previous meet
** Setting up the vagrant box
   1. Setting Vagrant for vlead
   2. Downloading and updating the dependency eg. building tomcat from
      source, dowloading maven, etc.

** Setting up CAS Demo
   We made a small client server which illustrated the use of CAS.
   The documnetation of the code can be found [[../client/index.org][here]]

** Updating the frontend
   Changes in the layouts
 
   After discussing the frontend layout and design, we can start
   working.

     
* Plan for next week
**   Implementing the SSO using the google single sign
      1. As our base server is ready, we can move to the next step which
      is integrating with google SSO
      2. We would need to make a google admin account:
	 2.1 It is works on a 2 week free trail period
	 2.2 This is followed by $5 monthly payment for using their services.
      3. We can also took for other services which do not charge for
         using their services.

** Updating the frontend
   After discussing the frontend layout and design, we can start
   working to give the desired output.
   
