#+TITLE: Oauth Service for VLEAD
#+AUTHOR: Shubh
#+DATE: [2016-07-11 Fri]
#+SETUPFILE: ./org-templates/level-0.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction
** Team 
   SSAD-57
** Project Description
   Building a Common Authentication System(CAS) for various VLEAD services.

** Team Members
   TEAM-57
         Himansh Sheoran (20161211)

         Shubh Maheshwari (20161170)

         Lovish Narang (20161158)

** Layout For Release-1
   In this presentation we wil discuss:
   
   1. Requirements
   2. Workflow
   3. Demo of CAS Server   
   4. Implementation
   5. Future Work and Goals   


* Application
  The =Oauth Service= authenticates and authorizes all the users using VLEAD(IIIT) microservices

1. [[./requirements/index.org][Problem Statement]]

2. [[./design/index.org][Design]]

3. [[./data-model/index.org][Data Model]]

4. [[./vlead-cas-overlay/index.org][CAS Server]]

5. [[./client/index.org][Demo Client Server]]
   
* Future Work
** Milestone-II
  Now instead of signing in through the credentials, the user should
  be able to sign in through omniauths such as google or facebook.

  Once clicked onto the link the user should be redirected to Google
  or Facebook login page and once successfully signed in should
  redirect back to the respective VLEAD portal.

** Milestone-III
  Integrate the various VLEAD prortals eg.LDS dashboard.
  
  Devlop several new packages for different VLEAD portals for easy
  integration with CAS.


* Tangle                                       :boilerplate:
#+BEGIN_SRC python :eval no :tangle __init__.py
print "Oauth Service"
#+END_SRC

