#+TITLE: Oauth Service Dashboard
#+AUTHOR: VLEAD
#+DATE: [2017-06-05 Mon]
#+PROPERTY: results output
#+PROPERTY: exports code
#+SETUPFILE: ../org-templates/level-1.org
#+options: ^:nil
#+LATEX: Literal LaTeX code for export

* Introduction 
  :PROPERTIES:
  :CUSTOM_ID: introduction
  :END: 
  This document describes all the requirements of =oauth-service=.

* Requirements
  :PROPERTIES:
  :CUSTOM_ID: requirements
  :END: 
	  
** Authentication of user
   1. VLEAD would like to develop a single sign on for all
      the VLEAD dashboards without the user signing on for
      each dashboard.  Example, when a user is signed in to
      outreach portal, and from outreach portal, when the
      user navigates to Vlabs analytics dashboard, the user
      should not be prompted for login.

   2. Also once signed-out the user no longer should be able to access
      respective VLEAD portals.

   3. VLEAD does not want to maintain passwords which means
      VLEAD likes to use gmail authentication. 

** COMMENT Common authentication between services
   Once the user logs in, he must be able to access all the
   services without authenticating again.
		


* System Requirements/Implementation
  Hence to build this portal we have decided to build in it *SPRING
  FRAMEWORK* using *MAVEN( PROJECT MANAGEMENT TOOL)* and *TOMCAT(
  Container)*. We are using *emacs* as our IDE for documenting all
  steps taken for deploying this service. We have also used VLEAD's
  *Vagrant Box* as our virtual environment. For buildig the relational
  model we have used ALLOY (FORMAL MODELLING TOOL).
