#+TITLE: Oauth Service Dashboard
#+AUTHOR: VLEAD
#+DATE: [2017-06-05 Mon]
#+PROPERTY: results output
#+PROPERTY: exports code
#+SETUPFILE: ../org-templates/level-1.org
#+options: ^:nil
#+LATEX: Literal LaTeX code for export

* Introduction 
  :PROPERTIES:
  :CUSTOM_ID: introduction
  :END: 
  This document describes all the requirements of =oauth-service=.

* Requirements
  :PROPERTIES:
  :CUSTOM_ID: requirements
  :END: 
	  
** Authentication of user
   1. VLEAD would like to develop a single sign on for all
      the VLEAD dashboards without the user signing on for
      each dashboard.  Example, when a user is signed in to
      outreach portal, and from outreach portal, when the
      user navigates to Vlabs analytics dashboard, the user
      should not be prompted for login.
   2. VLEAD does not want to maintain passwords which means
      VLEAD likes to use gmail authentication. 

   

** COMMENT Common authentication between services
   Once the user logs in, he must be able to access all the
   services without authenticating again.
		
